[build]
  # Directorio de publicación (donde están los archivos finales)
  publish = "."
  
  # No necesitamos comando de build ya que es HTML/CSS/JS puro
  command = ""

[build.environment]
  # Variables de entorno si las necesitas en el futuro
  NODE_VERSION = "18"

[[headers]]
  # Aplicar headers a todos los archivos
  for = "/*"
  [headers.values]
    # Habilitar CORS para fetch de data.json si lo usas
    Access-Control-Allow-Origin = "*"
    # Cache para archivos estáticos
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # Headers específicos para HTML (sin cache largo)
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  # Headers para JSON
  for = "*.json"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=300"

# Configuración para SPA routing (aunque usamos hash routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["!"]} 